name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller
        pip install requests colorama pystyle pillow phonenumbers whois qrcode dnspython cryptography pynput opencv-python numpy psutil pywin32 wmi
    
    - name: Build EXE
      run: |
        pyinstaller --onefile --collect-all requests --collect-all colorama --collect-all pystyle Glokk.py
    
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Glokk-EXE-Fixed
        path: dist/Glokk.exe
